services:
  - type: web
    name: n8n-job-bot
    env: node
    plan: free
    buildCommand: npm install -g n8n
    startCommand: n8n
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: N8N_HOST
        value: n8n-job-bot-3911.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-job-bot-3911.onrender.com/
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourStrongPassword
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-job-bot-3911.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: your-very-long-encryption-key
